<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CadastroCliente.CrossCutting</RootNamespace>
    <AssemblyName>CadastroCliente.CrossCutting</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CadastroCliente.Domain\CadastroCliente.Domain.csproj" />
  </ItemGroup>
</Project>
