<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CadastroCliente.Aplicacao</RootNamespace>
    <AssemblyName>CadastroCliente.Aplicacao</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CadastroCliente.Domain\CadastroCliente.Domain.csproj" />
    <ProjectReference Include="..\Cadastro.CrossCutting\CadastroCliente.CrossCutting.csproj" />
  </ItemGroup>
</Project>
